services:
  trainer:
    environment:
      - NUM_WORKERS=12
      - SELF_PLAY_DURATION_MS=900000
      - MCTS_THINK_TIME_MS=4200
      - EXPLORATION_MOVES=20
      - DIRICHLET_EPS=0.3
      - DIRICHLET_ALPHA=0.15
      - SYM_AUG_ROOT=8
      - MCTS_BATCH_SIZE=24
