from pathlib import Path
path = Path("src/components/Board.tsx")
text = path.read_text(encoding="utf-8")
old_option3 = "    const finalizeOption3 = useCallback(async (board: BoardMatrix) => {\n        try {\n            setSwap2Processing(true);\n            const resp = await fetch('/api/swap2/choose', {\n                method: 'POST',\n                headers: { 'Content-Type': 'application/json' },\n                body: JSON.stringify({ board }),\n            });\n            let aiColor: Player = 'black';\n            if (resp.ok) {\n                const data = await resp.json();\n                if (data?.aiColor === 'white') aiColor = 'white';\n            }\n            finalizeSwap2Opening(board, aiColor, 'white');\n        } catch (e) {\n            console.error('Swap2 choose failed:', e);\n            finalizeSwap2Opening(board, 'black', 'white');\n        }\n    }, [finalizeSwap2Opening]);"
new_option3 = "    const finalizeOption3 = useCallback(async (board: BoardMatrix) => {\n        try {\n            setSwap2Processing(true);\n            const resp = await fetchWithTimeout('/api/swap2/choose', {\n                method: 'POST',\n                headers: { 'Content-Type': 'application/json' },\n                body: JSON.stringify({ board }),\n            }, 4000);\n            let aiColor: Player = 'black';\n            if (resp.ok) {\n                const data = await resp.json();\n                if (data?.aiColor === 'white') aiColor = 'white';\n            } else {\n                console.warn('Swap2 choose returned non-OK status', resp.status);\n            }\n            const nextToMove: Player = 'black';\n            finalizeSwap2Opening(board, aiColor, nextToMove);\n        } catch (e) {\n            console.error('Swap2 choose failed:', e);\n            finalizeSwap2Opening(board, 'black', 'black');\n        }\n    }, [finalizeSwap2Opening]);"
if old_option3 not in text:
    raise SystemExit('finalizeOption3 block not found')
text = text.replace(old_option3, new_option3)
path.write_text(text, encoding="utf-8")
